### ISSUE TITLE
Unable to install certbot after installing linode-cli with pip

### ISSUE THREAD

**Issue by willemdh** [linode/linode-cli#49]
Hello,

I stumbled on issues with installation of certbot after installing linode-cli with pip. As I had this on an Ansible generated server after I added:

```
- name: Install Python packages
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - linode-cli
```

Error with `yum install certbot`

`Error unpacking rpm package python-urllib3-1.10.2-5.el7.noarch`

Not sure how or where this should be resolved.. Please also check https://github.com/certbot/certbot/issues/6245.

Grtz

Willem
