### ISSUE TITLE
Provide a markdown output format

### ISSUE THREAD

**Issue by displague** [linode/linode-cli#67]
Markdown could be handled in a similar way to the current `--text` tabbed delimited format.

Tabs would be replaced with ` | `, and the header line would be followed by a line with `---` field for each field name (also delimited by `|`).

**Comment by Dorthu** [comment]
I like it.  Is github's markdown flavor the best to go with?

**Comment by displague** [comment]
It's the one that I would use the most.  I don't believe I have used tools that wanted a different format for markdown tables.

RestructedText simple table export should be as easy to implement (assuming they take tabs and don't requires fixed column spaces).

**Comment by displague** [comment]
Would you be interested in supporting yaml as an output format?

```sh
$ linode-cli linodes list --json  | python -c 'import sys, yaml, json; j=json.loads(sys.stdin.read()); print yaml.safe_dump(j)'
```
```yaml
- id: 10967576
  image: linode/debian9
  ipv4: [32.144.57.47]
  label: linode10967576
  region: us-east
  status: running
  type: g6-nanode-1
- id: 11221635
  image: linode/ubuntu18.04
  ipv4: [55.33.222.44,192.168.22.33]
  label: linode11221635
  region: us-east
  status: running
  type: g6-standard-4
```

It would be nice to configure your preferred output format for the cli too.
